---

on:
  workflow_call:
    inputs:
      python-version:
        description: "The Python version to be used"
        default: "3.12"
        required: false
        type: string
      ruff-version:
        description: "The ruff version to be used"
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install ruff
        uses: astral-sh/ruff-action@v3
        with:
          version: ${{ inputs.ruff-version }}

      - name: Check for ruff issues
        run: ruff check --diff --output-format=github .

      - name: Check format
        run: ruff format --check
