---

on:
  workflow_call:
    secrets:
      actions-id-token-request-url:
        description: "The URL to GitHub's OIDC provider, use environment variable ACTIONS_ID_TOKEN_REQUEST_URL"
        required: true
      actions-id-token-request-token:
        description: "Bearer token for the request to the OIDC provider, use environment variable ACTIONS_ID_TOKEN_REQUEST_TOKEN"
        required: true
    inputs:
      python-version:
        description: "The Python version used during the build"
        default: "3.12"
        required: false
        type: string
      deploy-index:
        description: "The uv index to publish to"
        default: ""
        required: false
        type: string

jobs:
  build:
    name: Build Python package
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5

      - name: Build
        run: uv build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish-github:
    name: Publish on GitHub
    runs-on: ubuntu-latest
    permissions:                            
      id-token: write
      contents: write
    needs:
      - build
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Download the distribution packages
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Sign distribution packages
        uses: sigstore/gh-action-sigstore-python@v3.0.0
        with:
          inputs: |
            ./dist/*.tar.gz
            ./dist/*.whl

      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release create
          "${{ github.ref_name }}"
          --repo "${{ github.repository }}"
          --title "Release ${{ github.ref_name }}"
          --notes "see CHANGLOG.md"
          --latest

      - name: Upload artifacts and signatures to GitHub release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release upload
          "${{ github.ref_name }}" dist/**
          --repo "${{ github.repository }}"

  publish-pypi:
    name: Publish on PyPI
    runs-on: ubuntu-latest
    permissions:                            
      id-token: write
      contents: read
    needs:
      - publish-github
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      # required so that uv can read index information from pyproject.toml
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5

      - name: Download the distribution packages
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish to alternative index
        if: inputs.deploy-index != ''
        run: uv publish --trusted-publishing always --index ${{ inputs.deploy-index }}
        env:
          ACTIONS_ID_TOKEN_REQUEST_URL: ${{ secrets.actions-id-token-request-url }}
          ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ secrets.actions-id-token-request-token }}

      - name: Publish
        if: inputs.deploy-index == ''
        run: uv publish --trusted-publishing always
        env:
          ACTIONS_ID_TOKEN_REQUEST_URL: ${{ secrets.actions-id-token-request-url }}
          ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ secrets.actions-id-token-request-token }}
