---

on:
  workflow_call:
    inputs:
      python-version:
        description: "The Python version used during the build"
        default: "3.12"
        required: false
        type: string

jobs:
  build:
    name: Build Python package
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5

      - name: Build
        run: uv build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish-pypi:
    name: Publish on PyPI
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download the distribution packages
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish
        run: uv publish

  publish-github:
    name: Publish on GitHub
    runs-on: ubuntu-latest
    needs:
      - publish-pypi
    steps:
      - name: Sign dists
        uses: sigstore/gh-action-sigstore-python@v3.0.0
        with:
          inputs: >-
            ./dist/*.tar.gz
            ./dist/*.whl

      - name: Generate changelog
        id: changelog
        uses: janheinrichmerker/action-github-changelog-generator@v2.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          breakingLabels: backwards-incompatible,breaking
          removedLabels: removal
          enhancementLabels: feature,enhancement,improvement
          bugLabels: bug
          excludeLabels: skip-changelog
          output: ""  # to force output to stdout
          usernamesAsGithubLogins: true
          stripGeneratorNotice: true
          onlyLastTag: true

      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release create
          "${{ github.ref_name }}"
          --repo "${{ github.repository }}"
          --title "Release ${{ github.ref_name }}"
          --notes "${{ steps.changelog.outputs.changelog }}"
          --latest

      - name: Upload artifacts and signatures to GitHub release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release upload
          "${{ github.ref_name }}" dist/**
          --repo "${{ github.repository }}"
