---

on:
  workflow_call:
    inputs:
      python-version:
        description: "The Python version used during the build"
        default: "3.12"
        required: false
        type: string

jobs:
  python-build-package:
    name: Build Python package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install pypa/build
        run: python -m pip install build --user

      - name: Build a binary wheel and a source tarball
        run: python3 -m build

      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
