---

on:
  workflow_call:
    secrets:
      personal-access-token:
        required: true
        type: string
    inputs:
      python-version:
        description: "The Python version used during the build"
        default: "3.12"
        required: false
        type: string

jobs:
  tag-release:
    name: Tag release
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ inputs.python-version }}"

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          token: "${{ secrets.personal-access-token }}"

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5

      - name: Get version from pyproject.toml
        id: project-version
        run: echo "PROJECT_VERSION=$(uvx --from=toml-cli toml get --toml-path=pyproject.toml project.version)" >> $GITHUB_OUTPUT

      - name: Get latest git tag
        id: latest-tag
        run: echo "LATEST_TAG=$(git tag --list --sort=-v:refname | head -n 1 | grep -oE '([0-9]{1,}.[0-9]{1,}.[0-9]{1,})?')" >> $GITHUB_OUTPUT

      - name: Print current versions
        run: |
          echo "latest tag: $LATEST_TAG"
          echo "project version: $PROJECT_VERSION"
        env:
          LATEST_TAG: ${{ steps.latest-tag.outputs.LATEST_TAG }}
          PROJECT_VERSION: ${{ steps.project-version.outputs.PROJECT_VERSION }}

      - name: Get version diff
        id: version-diff
        # only compare if a previous git tag was found
        if: steps.latest-tag.outputs.LATEST_TAG != ''
        run: echo "VERSION_DIFF=$(uvx --from=semver pysemver compare ${{ env.PROJECT_VERSION }} ${{ env.LATEST_TAG }})" >> $GITHUB_OUTPUT
        env:
          LATEST_TAG: ${{ steps.latest-tag.outputs.LATEST_TAG }}
          PROJECT_VERSION: ${{ steps.project-version.outputs.PROJECT_VERSION }}

      - name: Create git tag
        uses: rickstaa/action-create-tag@v1
        # either we found a new release requirement or there was never a release made before
        if: (steps.latest-tag.outputs.LATEST_TAG != '' && steps.version-diff.VERSION_DIFF == 1) || steps.latest-tag.outputs.LATEST_TAG == ''
        with:
          tag: "v${{ steps.project-version.outputs.PROJECT_VERSION }}"
