---

on:
  workflow_call:

jobs:
  tag-release:
    name: Tag release
    runs-on: ubuntu-latest

    steps:
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Get version from pyproject.toml
        id: project-version
        run: echo "PROJECT_VERSION=$(uvx --from=toml-cli toml get --toml-path=pyproject.toml project.version)" >> $GITHUB_OUTPUT

      - name: Get latest git tag
        id: latest-tag
        run: echo "LATEST_TAG=$(git tag -l --sort=-creatordate | head -n 1 | grep -E '([0-9]{1,}.[0-9]{1,}.[0-9]{1,})?')" >> $GITHUB_OUTPUT

      - name: Get version diff
        id: version-diff
        # only compare if a previous git tag was found
        if: steps.latest-tag.outputs.LATEST_TAG != ''
        run: echo "VERSION_DIFF=$(uvx --from=semver pysemver compare ${{ env.PROJECT_VERSION }} ${{ env.LATEST_TAG }})" >> $GITHUB_OUTPUT
        env:
          PROJECT_VERSION: ${{ steps.project-version.outputs.PROJECT_VERSION }}
          LATEST_TAG: ${{ steps.latest-tag.outputs.LATEST_TAG }}

      - name: Create git tag
        uses: rickstaa/action-create-tag@v1
        # either we found a new release requirement or there was never a release made before
        if: (steps.latest-tag.outputs.LATEST_TAG != '' && steps.version-diff.VERSION_DIFF == 1) || steps.latest-tag.outputs.LATEST_TAG == ''
        with:
          tag: "v${{ steps.project-version.outputs.PROJECT_VERSION }}"
